ReachMeApp/Controllers/NavigationController.cs
using DomainLayer.Dto;
using DomainLayer.Model;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ServiceLayer.Service.Contract;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;

namespace ReachMeApp.Controllers
{
    public class NavigationController : Controller
    {
        private readonly IUser userService;

        public Uri baseAddres { get; set; }
        public HttpClient client { get; set; }

        public NavigationController(IUser userService)
        {
            baseAddres = new Uri("https://localhost:44348/");
            client = new HttpClient();
            client.BaseAddress = baseAddres;
            this.userService = userService;
        }

        public IActionResult Post()
        {
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Request.Cookies["Jwt"]);
            HttpResponseMessage response = client.GetAsync(client.BaseAddress + "api/Post").Result;

            if (response.IsSuccessStatusCode)
                return View();
            return RedirectToAction("Login", "Home");
        }

        [HttpPost]
        public IActionResult Post(PostDto postDto)
        {
            postDto.ImageData = userService.ConvertImage(postDto.ImageFile);
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Request.Cookies["Jwt"]);
            string data = JsonConvert.SerializeObject(postDto);
            StringContent content = new StringContent(data, Encoding.UTF8, "application/json");

            HttpResponseMessage response = client.PostAsync(client.BaseAddress + "api/Post", content).Result;

            if (response.IsSuccessStatusCode)
                return View();
            return RedirectToAction("Index", "User");
        }

        public IActionResult Search(NavigationDto navigationDto)
        {
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Request.Cookies["Jwt"]);
            string data = JsonConvert.SerializeObject(navigationDto.SearchString);
            StringContent content = new StringContent(data, Encoding.UTF8, "application/json");

            HttpResponseMessage response = client.PostAsync(client.BaseAddress + "api/Search", content).Result;
            List<User> searchResults = JsonConvert.DeserializeObject<List<User>>(response.Content.ReadAsStringAsync().Result);

            if (response.IsSuccessStatusCode)
                return View(searchResults);
            return RedirectToAction("Login", "Home");
        }
    }
}

ReachMeApp/Views/Shared/NavigationBar.cshtml
@model DomainLayer.Dto.NavigationDto
@using DomainLayer.Model
@using ServiceLayer.Service.Implementation
@using Microsoft.AspNetCore.Http;
@using System.Security.Claims;
@using System.IdentityModel.Tokens.Jwt
@inject HttpContextAccessor httpContextAccessor
@inject UserService Service

@{
    ViewData["Title"] = "Index";
    int GetCurrentId()
    {
        var token = httpContextAccessor.HttpContext.Request.Cookies["Jwt"];
        var handler = new JwtSecurityTokenHandler();
        var jwtSecurityToken = handler.ReadJwtToken(token);
        var tokenS = jwtSecurityToken as JwtSecurityToken;
        return int.Parse(tokenS.Claims.First(claim => claim.Type == ClaimTypes.NameIdentifier).Value);
    }
    User currentUser = (Model.CurrentUser == null) ? Service.GetUser(GetCurrentId().ToString()) : Model.CurrentUser;
}

<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand home-bar-title">Reach Me</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="User" asp-action="Home">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="User" asp-action="Index">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="User" asp-action="Discover">Discover</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="User" asp-action="Account">Account</a>
                    </li>
                </ul>
                <form class="input-group w-25 justify-content-end" method="post" asp-controller="Navigation" asp-action="Search">
                    <input type="text" class="form-control rounded" asp-for="@Model.SearchString" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
                    <input type="submit" class="btn btn-outline-primary" value="Search">
                </form>
                <ul class="navbar-nav flex-grow-1 d-flex justify-content-end">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Navigation" asp-action="Post"><img class="postIcon" /></a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-outline-danger" asp-controller="Home" asp-action="Logout">Logout</a>
                    </li>
                </ul>
                <div class="flex ml-1 text-center">
                    @if (currentUser.ProfilePic != null)
                    {
                        <img class="navbar-picture rounded-circle" src="data:image/jpg;base64,@currentUser.ProfilePic" />
                    }
                    else
                    {
                        <img class="navbar-picture rounded-circle" src="~/images/defaultProfilePicture.jpeg" />
                    }
                    <p>@currentUser.Username</p>
                </div>
            </div>
        </div>
    </nav>
</header>

ReachMeApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ReachMeApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/HomeBarCSS.css" />
    <base href="~/" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>