ReachMeApp/Controllers/ForgotPasswordController.cs
using DomainLayer.Dto;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Net.Http;
using System.Text;

namespace ReachMeApp.Controllers
{
    public class ForgotPasswordController : Controller
    {
        public Uri baseAddres { get; set; }
        public HttpClient client { get; set; }

        public ForgotPasswordController()
        {
            baseAddres = new Uri("https://localhost:44389/");
            client = new HttpClient();
            client.BaseAddress = baseAddres;
        }

        public IActionResult Index() => View();

        [HttpPost]
        public IActionResult Index(ForgotPasswordDto forgotPassword)
        {
            string data = JsonConvert.SerializeObject(forgotPassword);
            StringContent content = new StringContent(data, Encoding.UTF8, "application/json");

            HttpResponseMessage response = client.PostAsync(client.BaseAddress + "api/ForgotPassword/SendRecoverEmail", content).Result;

            if (response.IsSuccessStatusCode)
                return RedirectToAction("Index", "Home");
            return View();
        }

        [HttpGet]
        [Route("ForgotPassword/RecoverPassword/{encryptedEmail}")]
        public IActionResult RecoverPassword() => View();

        [HttpPost]
        [Route("ForgotPassword/RecoverPassword/{encryptedEmail}")]
        public IActionResult RecoverPassword(RecoverPasswordDto recoverPasswordDto, string encryptedEmail)
        {
            recoverPasswordDto.EncryptedEmail = encryptedEmail;

            string data = JsonConvert.SerializeObject(recoverPasswordDto);
            StringContent content = new StringContent(data, Encoding.UTF8, "application/json");

            HttpResponseMessage response = client.PostAsync(client.BaseAddress + "api/ForgotPassword/RecoverPassword", content).Result;

            if (response.IsSuccessStatusCode)
                return RedirectToAction("Login", "Home");
            return View();
        }
    }
}

ReachMeApp/Controllers/HomeController.cs
using DomainLayer.Dto;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Net.Http;
using System.Text;

namespace ReachMeApp.Controllers
{
    public class HomeController : Controller
    {
        public Uri baseAddres { get; set; }
        public HttpClient client { get; set; }

        public HomeController()
        {
            baseAddres = new Uri("https://localhost:44389/");
            client = new HttpClient();
            client.BaseAddress = baseAddres;
        }

        public IActionResult Index() => View();

        public IActionResult Logout()
        {
            if (HttpContext.Request.Cookies["Jwt"] != null)
                Response.Cookies.Delete("Jwt");
            return View("Index");
        }

        public IActionResult Login()
        {
            TempData.Remove("InvalidLogin");
            return View();
        }

        [HttpGet("Login")]
        public IActionResult Login(int x)
        {
            TempData.Remove("InvalidLogin");
            return View();
        }

        [HttpPost("Login")]
        public IActionResult Login(LoginDto loginUser)
        {
            StringContent content = Serialize<LoginDto>(loginUser);
            HttpResponseMessage response = client.PostAsync(client.BaseAddress + "api/LoginRegister/Login", content).Result;

            string token = response.Content.ReadAsStringAsync().Result;
            CookieOptions cookieOptions = new CookieOptions();
            cookieOptions.Expires = DateTime.Now.AddMinutes(15);
            Response.Cookies.Append("Jwt", token, cookieOptions);

            if (response.IsSuccessStatusCode)
                return RedirectToAction("Index","User");
            TempData["InvalidLogin"] = "User do not exist or is not verified";
            return View();
        }

        public IActionResult Register()
        {
            TempData.Remove("InvalidRegister");
            return View();
        }

        [HttpPost("Register")]
        public IActionResult Register(RegisterDto newUser)
        {
            StringContent content = Serialize<RegisterDto>(newUser);
            HttpResponseMessage response = client.PostAsync(client.BaseAddress + "api/LoginRegister/Register", content).Result;

            if (response.IsSuccessStatusCode)
                return RedirectToAction("Index");
            TempData["InvalidRegister"] = "Email or username already in use";
            return View();
        }

        [HttpGet]
        [Route("Home/VerifyEmail/{id}")]
        public IActionResult VerifyEmail(string id)
        {
            StringContent content = Serialize<string>(id);
            HttpResponseMessage response = client.PostAsync(client.BaseAddress + "api/LoginRegister/VerifyEmail", content).Result;

            if(response.IsSuccessStatusCode)
                return RedirectToAction("Index");
            return BadRequest("Something went wrong, verification failed");
        }

        private StringContent Serialize<T>(T obj)
        {
            string data = JsonConvert.SerializeObject(obj);
            StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
            return content;
        }
    }
}

ReachMeApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}
@using ReachMeApp.Components

@(await Html.RenderComponentAsync<HomeBar>(RenderMode.ServerPrerendered))
<script src="_framework/blazor.server.js"></script>

<link rel="stylesheet" href="~/css/HomeCSS.css" />

<div class="text-center">
    <h1 class="display-4">Welcome to Reach Me</h1>
    <h3>Stay in touch with your friends</h3>
</div>

ReachMeApp/Views/Home/Login.cshtml
@model DomainLayer.Dto.LoginDto
@using ReachMeApp.Components 

@{
    ViewData["Title"] = "Login";
}

@(await Html.RenderComponentAsync<HomeBar>(RenderMode.ServerPrerendered))
<script src="_framework/blazor.server.js"></script>

<link rel="stylesheet" href="~/css/HomeCSS.css" />

<div class="d-flex flex-column align-items-center">
    <h1>Already have an account?</h1><br />
    <h3>Log in now</h3>
</div>

<hr />

<div class="d-flex justify-content-center">
    <div class="col-md-4">
        <form asp-action="Login">
            @if (TempData.ContainsKey("InvalidLogin") == true)
            {
                <span class="text-danger">@TempData["InvalidLogin"]</span>
            }
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Username" class="form-control" placeholder="Username" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">

                <input type="password" asp-for="Password" class="form-control" placeholder="Password" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group d-flex justify-content-center">
                <a asp-controller="ForgotPassword" asp-action="Index">Forgot password?</a>
            </div>
            <div class="form-group d-flex justify-content-center">
                <input type="submit" value="LOG IN" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ReachMeApp/Views/Home/Register.cshtml
@model DomainLayer.Dto.RegisterDto
@using ReachMeApp.Components

@{
    ViewData["Title"] = "Register";
}

@(await Html.RenderComponentAsync<HomeBar>(RenderMode.ServerPrerendered))
<script src="_framework/blazor.server.js"></script>

<link rel="stylesheet" href="~/css/HomeCSS.css" />

<div class="d-flex flex-column align-items-center">
    <h1>You don't have an account?</h1><br />
    <h3>Register now</h3>
</div>

<hr />

<div class="d-flex justify-content-center">
    <div class="col-md-4">
        <form asp-action="Register">
            @if (TempData.ContainsKey("InvalidRegister") == true)
            {
                <span class="text-danger">@TempData["InvalidRegister"]</span>
            }
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Email" class="form-control" placeholder="E-mail" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="Username" class="form-control" placeholder="Username" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="password" asp-for="Password" class="form-control" placeholder="Password" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="password" asp-for="RepeatPassword" class="form-control" placeholder="Repeat password" />
                <span asp-validation-for="RepeatPassword" class="text-danger"></span>
            </div>
            <div class="form-group d-flex justify-content-center">
                <input type="submit" value="REGISTER" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ReachMeApp/Views/Home/VerifyEmail.cshtml
@{
    ViewData["Title"] = "Verify Email";
}
@using ReachMeApp.Components

@(await Html.RenderComponentAsync<HomeBar>(RenderMode.ServerPrerendered))
<script src="_framework/blazor.server.js"></script>

<link rel="stylesheet" href="~/css/HomeCSS.css" />

<div class="text-center">
    <h1 class="display-4">Welcome to ReachMe</h1>
    <h3>Your account is now verified!</h3>
</div>